<script type="text/javascript">
    jQuery(document).ready(function($) {
        jQuery(this).on('click', 'form#shipping-zip-form input', function () {
            dataLayer.push({
                'event':'VirtualPageview',
                'virtualPageURL':'/#' + jQuery(this).attr('name') + ''
            });
        });
        jQuery(this).on('click', 'input[name*="estimate_method"]', function () {
            dataLayer.push({
                'event':'VirtualPageview',
                'virtualPageURL':'/#' + jQuery(this).attr('name') + ''
            });
        });

    });
</script>